language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - mkdir ~/cmake_tmp
  - cd ~/cmake_tmp
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo cp -r cmake-3.2.3-Linux-x86_64/bin/* /usr/local/bin
  - sudo cp -r cmake-3.2.3-Linux-x86_64/doc/* /usr/local/doc
  - sudo cp -r cmake-3.2.3-Linux-x86_64/share/* /usr/local/share

before_script:
  - git submodule update --init --recursive
  - cd build
  - cmake .. -DLIBSDP_ENABLE_TESTS=ON

script:
  - make
  - make test