language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - git submodule update --init --recursive
  - cd build
  - cmake .. -DLIBSDP_ENABLE_TESTS=ON

script:
  - make
  - cd /home/travis/build/Cyberunner23/libSDP/test/compressionTests/DEFLATECompressionTest
  - ls
  - cd /home/travis/build/Cyberunner23/libSDP/test/compressionTests/lz4CompressionTest
  - ls
  - cd /home/travis/build/Cyberunner23/libSDP/test/encryptionTests/XSalsa20EncryptionTest
  - ls