language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

install:
  - if ["$CXX" == "g++"]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if ["$CXX" == "g++"]; then sudo apt-get update -qq; fi
  - if ["$CXX" == "g++"]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if ["$CXX" == "g++"]; then update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi

before_script:
  - git submodule update --init --recursive
  - cd build
  - cmake .. -DLIBSDP_ENABLE_TESTS=ON

script:
  - make
  - make test