language: cpp
sudo: false

os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt: &gcc5
     packages:
       - gcc-5
       - g++-5
       - clang-3.7
     sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.7

install:
  - if [ ! "$(ls -A cmake-3.4.0-Linux-x86_64)" ]; then
      wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz
      && tar xf cmake-3.4.0-Linux-x86_64.tar.gz
      && rm cmake-3.4.0-Linux-x86_64.tar.gz;
    fi

before_script:
  - if [ "$CXX" == "clang++" ]; then
        export CXXCOMPILER="clang"
        && export CC="clang-3.7"
        && export CXX="clang++-3.7"
        && clang-3.7 --version
        && clang++-3.7 --version;
    fi
  - if [ "$CXX" == "g++" ]; then
        export CXXCOMPILER="gcc"
        && export CC="gcc-5"
        && export CXX="g++-5"
        && gcc-5 --version
        && g++-5 --version;
    fi
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - ../cmake-3.4.0-Linux-x86_64/bin/cmake .. -DLIBSDP_ENABLE_TESTS=ON

script:
  - make

cache:
  directories:
    - cmake-3.4.0-Linux-x86_64